openapi: 3.1.0
info:
  version: 1.0.0
  title: Phonebook app
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  description:
    This is a documentation of Phonebook app
tags:
  - name: Phonebook
    description: Operations about contacts.
  - name: Auth
    description: Auth operations.
servers:
  - url: https://nodejs-hw-mongodb-7-3kd1.onrender.com
  - url: https://mysite.com
paths:
  /contacts:
    get:
      $ref: ../swagger/paths/contacts/get.yaml
    post:
      $ref: ../swagger/paths/contacts/post.yaml
  /{id}:
    get:
      $ref: ../swagger/paths/contacts/{id}/get.yaml
    delete:
      $ref: ../swagger/paths/contacts/{id}/delete.yaml
    patch:
      $ref: ../swagger/paths/contacts/{id}/patch.yaml
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
